language: generic

os:
  - linux
  - osx

sudo: required

services:
  - docker

before_install:
  - bash -e ci/travis_before_install.sh
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export TARGET_NAME=darwin-x64; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export TARGET_NAME=linux-x64; fi

before_script:
  - IS_PPX_BS_CSS_CI=true yarn
  - ./ci/before_script_$TRAVIS_OS_NAME.sh

script:
  - ./ci/build_script_$TRAVIS_OS_NAME.sh
  # - make test
  # - NODE_ENV=production make test
  - mv ppx_bs_css.exe ppx_bs_css-$TARGET_NAME.exe

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: ppx_bs_css-*.exe
  api_key:
    secure: $GITHUB_API_KEY
  on:
    tags: true


jobs:
  include:
    - stage: Wait for Windows binaries to become available
      addons:
        apt:
          sources: []
          packages: []
      before_install: skip
      before_script: skip
      deploy: []
      script: bash -e ci/wait_for_builds.sh

    - stage: Deploy to npmjs
      addons:
        apt:
          sources: []
          packages: []
      before_install: skip
      before_script: skip
      script:
        - bash -e ci/download_binaries.sh
      deploy:
        provider: npm
        email: jakub.korzeniowski@gmail.com
        api_key:
          secure: $NPM_API_KEY
        on:
          tags: true
        skip_cleanup: true
