name: ppx_bs_css

trigger:
  - master

jobs:
  - template: .ci/release/pipeline.yml
    parameters:
      name: "macOS"
      vmImage: "macOS-latest"
      platform: "macOS"

  - template: .ci/release/pipeline.yml
    parameters:
      name: "Linux"
      vmImage: "ubuntu-latest"
      platform: "Linux"

  - template: .ci/release/pipeline.yml
    parameters:
      name: "Windows"
      vmImage: "windows-latest"
      platform: "Windows"

  - job: Release
    pool:
      vmImage: "ubuntu-latest"
    dependsOn:
      - macOS
      - Linux
      - Windows
    steps:
      - template: .ci/release/bundle.yml
      - task: Npm@1
        displayName: "npm publish"
        inputs:
          command: custom
          workingDir: "_release"
          verbose: false
          customCommand: "publish"
          customEndpoint: "npm-publish-package"
